### PR TITLE
[DOXIA-699] Add failing test case

### PR DESCRIPTION
**Pull request by kwin**

### CODE REVIEW

**Comment by kwin** [comment]
@michael-o Can you have a look why this test fails?

**Comment by michael-o** [comment]
Looking into...

**Review by michael-o — COMMENTED** [review]
@kwin The input file is invalid because it has not been generated by Doxia 2.

**Comment by kwin** [comment]
Why is it invalid? Every valid XHTML should work with the Doxia parser.

**Comment by michael-o** [comment]
> Why is it invalid? Every valid XHTML should work with the Doxia parser.

Very good question, at least the diff doesn't look suspicious: https://github.com/apache/maven-doxia/commit/13138a96894b0ad341a36a069595ad5bcea0ba7c

**Comment by michael-o** [comment]
Maybe this is it:
```
- <h2><a name="Feature_Summary"></a>Feature Summary</h2>
+ <h1>Feature Summary</h1>
```

Give it a shot.

**Comment by kwin** [comment]
I wrote that already in the JIRA ticket: the culprit is https://github.com/apache/maven-doxia/blob/37173794270ee68894aac0e252dcb87545770952/doxia-core/src/main/java/org/apache/maven/doxia/parser/Xhtml5BaseParser.java#L631

**Comment by michael-o** [comment]
But the exception is totally misleading...

**Comment by michael-o** [comment]
I'd say Doxia should not try to heal the document...

**Comment by kwin** [comment]
> I'd say Doxia should not try to heal the document...

Maybe that is rather up for discussion with a follow-up issue. Right now I would only want to fix the missing close element method.

**Comment by michael-o** [comment]
> > I'd say Doxia should not try to heal the document...
> 
> Maybe that is rather up for discussion with a follow-up issue. Right now I would only want to fix the missing close element method.

Agree...

**Comment by kwin** [comment]
The PR at #162 provides a simpler reproducer/test case of this issue.

**Comment by kwin** [comment]
Superseded by #162.

**Comment by jira-importer** [comment]
Resolve #836

**Pull request closed without merging**
