### PR TITLE
Upgrade to JDK8, junit 5 and @Inject annotations

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by michael-o** [comment]
Wow, this is insane! I remember that `@Inject` has a slightly different notion comparented to `@Requirement`. Does it matter here or can we replace it 1:1?

**Comment by michael-o** [comment]
It is possible from your PoV to split JDK 8 upgrade and the rest with two separate issues? This should make the change visiable in the changelog for next milestone.

**Comment by gnodet** [comment]
> Wow, this is insane! I remember that `@Inject` has a slightly different notion comparented to `@Requirement`. Does it matter here or can we replace it 1:1?

Not much difference afaik.  The `role` is mapped to the class name (and usually not of any use) and the `hint` is covered by the `@Name` annotation.  There's not real use case for it when injecting, because the concrete class is usually injected, for example in https://github.com/apache/maven-doxia/pull/92/files#diff-04c5c280b39239f19337818da8190fb25ce92c6e59d075520163f8e59351fac2L45, so guide has no real choice.  If we were injecting the `Parser` class, we'd have to specify `@Inject @Named( "fml" )` for example.

**Comment by gnodet** [comment]
> It is possible from your PoV to split JDK 8 upgrade and the rest with two separate issues? This should make the change visiable in the changelog for next milestone.

Yes, though the upgrade to JDK8 will be a rather small commit and will obviously be a requirement for the follow-up commit.  I'll force push two commits in this PR if that's ok for you.

**Review by michael-o — CHANGES_REQUESTED** [review]
I see the following warnings:
```
INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ doxia-core ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.5:compile
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ doxia-module-apt ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ doxia-module-fml ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ doxia-module-xdoc ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ doxia-module-xhtml ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
[INFO] --- maven-dependency-plugin:3.1.1:analyze (default-cli) @ doxia-module-markdown ---
[WARNING] Used undeclared dependencies found:
[WARNING]    javax.inject:javax.inject:jar:1:compile
```
 can you added them?

**Pull request closed without merging**
