### PR TITLE
Upgrade Plexus Utils and XML

### PR DESCRIPTION
**Pull request by michael-o**

### CODE REVIEW

**Comment by michael-o** [comment]
@basilcrow I think you are after this, no?

**Comment by michael-o** [comment]
@basil

**Comment by basil** [comment]
Yes, this sounds like the cause of the Enforcer warnings with a Maven 3 baseline. Based on https://codehaus-plexus.github.io/plexus-utils/

> keep `plexus-xml` to 3 if you want Maven 3 compatibility, as `plexus-xml` 4 works only in Maven 4

**Comment by cstamas** [comment]
I tend to keep all Maven-3 "thing" deps at p-u 3... and Maven-4 "things" at p-u 4 + p-x

@gnodet

**Comment by michael-o** [comment]
> I tend to keep all Maven-3 "thing" deps at p-u 3... and Maven-4 "things" at p-u 4 + p-x
> 
> @gnodet

Note that we have now done the opposite everywhere for Maven 3.  Means, two deps.

**Comment by gnodet** [comment]
> > I tend to keep all Maven-3 "thing" deps at p-u 3... and Maven-4 "things" at p-u 4 + p-x
> 
> > 
> 
> > @gnodet
> 
> 
> 
> Note that we have now done the opposite everywhere for Maven 3.  Means, two deps.

Maven 3: p-u 4 and p-x 3
Maven 4: p-u 4 and p-x 4

**Comment by michael-o** [comment]
Any objections here still?

**Pull request merged**
