### PR TITLE
[DOXIA-737] [REGRESSION] Making EmitAnchorsForIndexableEntries by def…

### PR DESCRIPTION
**Pull request by michael-o**
…ault does not extract document titles anymore

This closes #214

### CODE REVIEW

**Review by kwin — APPROVED** [review]
Thanks for fixing this. Wondering though why there is no IT/UT having caught that. Probably time to add one…

**Comment by kwin** [comment]
BTW: There is no need for git commit messages which close the PR.. This is only useful when referencing a GitHub issue.

**Comment by michael-o** [comment]
> BTW: There is no need for git commit messages which close the PR.. This is only useful when referencing a GitHub issue.

I know, I do it on purpose to establish the connection between the commit and the PR when browsing `git log` from the terminal. Metadata.

**Comment by michael-o** [comment]
> Thanks for fixing this. Wondering though why there is no IT/UT having caught that. Probably time to add one…

Do you have an idea from the top of your head? Took me some time to tackle this. Don't whether it should be in Doxia or somewhere later this test.

**Comment by kwin** [comment]
The test should be in Doxia. But I won’t have time to look into this the next two weeks. Should not block merging though

**Comment by jira-importer** [comment]
Resolve #864

**Pull request merged**
