### PR TITLE
Expose no-op sink

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
I would use it for this: https://issues.apache.org/jira/browse/MPMD-403?focusedCommentId=17880071&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17880071

**Review by cstamas — APPROVED** [review]
makes sense

**Comment by michael-o** [comment]
Before I consent this I will take a look at the issue with PMPD. This should not have happened. In standalone mode a preset skin should be used.

**Comment by michael-o** [comment]
@pzygielo Are we good to close this one?

**Pull request closed without merging**
