### PR TITLE
[DOXIA-566] Upgrade dependences and plugin versions

### PR DESCRIPTION
**Pull request by slachiewicz**

### CODE REVIEW

**Comment by slachiewicz** [comment]
I have updated dependnces and fixed test after update

**Comment by hboutemy** [comment]
please don't update plugins: this will happen with parent pom. AFAIK, no hurry.

upgrade of dependencies is what I'd like to merge only: can you update the PR, please?

**Comment by slachiewicz** [comment]
ok, plugin updates removed

**Comment by hboutemy** [comment]
PR merged
thank you

**Comment by jira-importer** [comment]
Resolve #532

**Pull request closed without merging**
