### PR TITLE
rollback Java 7 breaking change

### PR DESCRIPTION
**Pull request by elharo**
@michael-o @bertysentry

### CODE REVIEW

**Comment by bertysentry** [comment]
Personally, I'm in favor of simply adding a commit that fixes the problem rather than reverting and then recommitting the same code plus the fix. But that's a git philosophy question, so I'll let you guys decide ;-)

**Comment by elharo** [comment]
That's a moot point until such a fix exists.

**Comment by bertysentry** [comment]
I have it. I'll submit my PR in a moment.

**Comment by michael-o** [comment]
Yepp, I need also a day or two to digest.

**Comment by bertysentry** [comment]
No problem. Remember we also have [this PR](https://github.com/apache/maven-doxia/pull/54) that restores the Java 7 compatibility. Thanks!

**Pull request closed without merging**
