### PR TITLE
[DOXIA-619] Sink.sectionTitle1() creates <h2> instead of <h1>

### PR DESCRIPTION
**Pull request by michael-o**
https://issues.apache.org/jira/browse/DOXIA-619
Completely handle section handling which will now consistently apply
between h1 and h5 for HTML and for Markdown. The partially unused or
incorrectly mapped section h6 has been dropped.

This closes #99

### CODE REVIEW

**Review by bertysentry — APPROVED** [review]
Very nice!

We need to make sure this doesn't break the tests in **maven-site-plugin**

**Comment by michael-o** [comment]
I have a followup branch for DOXIASITETOOLS ready locally. Please carefully look whether this is complete or not.

**Comment by michael-o** [comment]
@bertysentry Have a look at https://github.com/apache/maven-doxia-sitetools/commit/b002a410296a248074eccd3a3af95b0ff7d697af.

**Comment by bertysentry** [comment]
> @bertysentry Have a look at [apache/maven-doxia-sitetools@b002a41](https://github.com/apache/maven-doxia-sitetools/commit/b002a410296a248074eccd3a3af95b0ff7d697af).

Ha ha! Must have been a lot of fun to update all these! To me everything looks in order.

You updated the *Parser* classes to be consistent with the *Sink* classes, that's even better than what I first suggested. You still need to check the **maven-site-plugin** integration tests.

This is a nice change, well done!

**Comment by michael-o** [comment]
> > @bertysentry Have a look at [apache/maven-doxia-sitetools@b002a41](https://github.com/apache/maven-doxia-sitetools/commit/b002a410296a248074eccd3a3af95b0ff7d697af).
> 
> Ha ha! Must have been a lot of fun to update all these! To me everything looks in order.

Yep, stupid trial and error.

> You updated the _Parser_ classes to be consistent with the _Sink_ classes, that's even better than what I first suggested. You still need to check the **maven-site-plugin** integration tests.

Yes, it strive for consistency and don't like surprises. Actually, I did run all MSITE ITs, they all pass. I have a local branch prepared with MSITE 4.x and upcoming Doxia/Doxia Sitetools. I do test the entire chain.
 
> This is a nice change, well done!

Thanks! Waiting for @hboutemy to go through as well.

**Review by hboutemy — APPROVED** [review]
looks like a good idea: I reviewed history, I can't find any good reason why at the very beginning, it was chosen not to align HTML header sections numbers with Doxia levels

aligning will make Doxia Sink API easier to understand

**Comment by jira-importer** [comment]
Resolve #788

**Pull request closed without merging**
