### PR TITLE
XHTML5 support for maven-doxia (redux)

### PR DESCRIPTION
**Pull request by minfrin**
https://issues.apache.org/jira/browse/DOXIA-575

### CODE REVIEW

**Comment by michael-o** [comment]
I have now pushed a branch and get this error:

```
[ERROR] Failures:
[ERROR]   Xhtml5BaseSinkTest.testContent:518 expected:<<main>[]
]div class="content...> but was:<<main>[
<div class="content...>
[INFO]
[ERROR] Tests run: 241, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by minfrin** [comment]
I built the project on a different VM with a completely clean .m2 directory and uncovered a non-checked-in part of the code.

I currently get this:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Doxia ............................................. SUCCESS [19.979s]
[INFO] Doxia :: Logging API .............................. SUCCESS [5.326s]
[INFO] Doxia :: Sink API ................................. SUCCESS [3.187s]
[INFO] Doxia :: Test Documents ........................... SUCCESS [3.101s]
[INFO] Doxia :: Core ..................................... SUCCESS [32.218s]
[INFO] Doxia :: Modules .................................. SUCCESS [1.805s]
[INFO] Doxia :: APT Module ............................... SUCCESS [11.825s]
[INFO] Doxia :: Confluence Module ........................ SUCCESS [9.403s]
[INFO] Doxia :: Simplified DocBook Module ................ SUCCESS [8.694s]
[INFO] Doxia :: FML Module ............................... SUCCESS [5.062s]
[INFO] Doxia :: FO Module ................................ SUCCESS [20.860s]
[INFO] Doxia :: iText Module ............................. SUCCESS [7.074s]
[INFO] Doxia :: Latex Module ............................. SUCCESS [4.978s]
[INFO] Doxia :: RTF Module ............................... SUCCESS [9.964s]
[INFO] Doxia :: TWiki Module ............................. SUCCESS [7.848s]
[INFO] Doxia :: XDoc Module .............................. SUCCESS [5.734s]
[INFO] Doxia :: XHTML Module ............................. SUCCESS [5.810s]
[INFO] Doxia :: XHTML5 Module ............................ SUCCESS [6.334s]
[INFO] Doxia :: Markdown Module .......................... SUCCESS [22.975s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3:15.044s
[INFO] Finished at: Sun Apr 28 19:25:00 UTC 2019
[INFO] Final Memory: 55M/225M
[INFO] ------------------------------------------------------------------------

**Comment by michael-o** [comment]
Please rebase your latest changes against the branch I have pushed.

**Comment by minfrin** [comment]
I've been googling how to rebase a branch for the last hour, and it has me stumped. The closest I got was an attempt that saw me trying to push to apache/maven-doxia instead of minfrin/maven-doxia, and obviously that won't work.

Can you confirm what I need to do?

**Comment by michael-o** [comment]
Checkout my branch, and perform a cherry pick on your two subsequent commits, that's it.

**Comment by michael-o** [comment]
I have force-pushed an updated branch. The issue still persists:

```

[INFO]                                                                           [INFO] Results:                                                                  [INFO]                                                                           [ERROR] Failures:                                                                [ERROR]   Xhtml5BaseSinkTest.testContent:518 expected:<[]                  ]div class="content...> but was:<[
--
```

**Comment by minfrin** [comment]
Thanks for this.

I checked out a completely clean copy of the DOXIA-575 branch, then deleted my .m2 directory and ran "mvn clean install", and got success again:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Doxia ............................................. SUCCESS [33.764s]
[INFO] Doxia :: Logging API .............................. SUCCESS [9.715s]
[INFO] Doxia :: Sink API ................................. SUCCESS [3.800s]
[INFO] Doxia :: Test Documents ........................... SUCCESS [3.060s]
[INFO] Doxia :: Core ..................................... SUCCESS [1:21.713s]
[INFO] Doxia :: Modules .................................. SUCCESS [1.836s]
[INFO] Doxia :: APT Module ............................... SUCCESS [8.084s]
[INFO] Doxia :: Confluence Module ........................ SUCCESS [7.457s]
[INFO] Doxia :: Simplified DocBook Module ................ SUCCESS [9.265s]
[INFO] Doxia :: FML Module ............................... SUCCESS [5.685s]
[INFO] Doxia :: FO Module ................................ SUCCESS [21.917s]
[INFO] Doxia :: iText Module ............................. SUCCESS [7.573s]
[INFO] Doxia :: Latex Module ............................. SUCCESS [6.841s]
[INFO] Doxia :: RTF Module ............................... SUCCESS [9.115s]
[INFO] Doxia :: TWiki Module ............................. SUCCESS [9.661s]
[INFO] Doxia :: XDoc Module .............................. SUCCESS [6.364s]
[INFO] Doxia :: XHTML Module ............................. SUCCESS [6.522s]
[INFO] Doxia :: XHTML5 Module ............................ SUCCESS [6.516s]
[INFO] Doxia :: Markdown Module .......................... SUCCESS [12.388s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:15.348s
[INFO] Finished at: Sun Apr 28 22:08:47 UTC 2019
[INFO] Final Memory: 58M/217M
[INFO] ------------------------------------------------------------------------

**Comment by minfrin** [comment]
Code was developed on MacOS Mojave, testing above done on CentOS7:

[minfrin@localhost maven-doxia-DOXIA-575]$ rpm -q -a | grep release
epel-release-7-11.noarch
centos-release-7-5.1804.5.el7.centos.x86_64
[minfrin@localhost maven-doxia-DOXIA-575]$ rpm -q -a | grep maven-3
maven-3.0.5-17.el7.noarch

**Comment by michael-o** [comment]
It also fails on Jenkins: https://builds.apache.org/job/maven-box/job/maven-doxia/job/DOXIA-575/2/testReport/junit/org.apache.maven.doxia.sink.impl/Xhtml5BaseSinkTest/windows_jdk8___Build_windows_jdk8___testContent/

**Comment by minfrin** [comment]
Works on MacOS Mojave:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Doxia 1.9-SNAPSHOT:
[INFO] 
[INFO] Doxia .............................................. SUCCESS [  2.845 s]
[INFO] Doxia :: Logging API ............................... SUCCESS [  2.731 s]
[INFO] Doxia :: Sink API .................................. SUCCESS [  1.285 s]
[INFO] Doxia :: Test Documents ............................ SUCCESS [  1.372 s]
[INFO] Doxia :: Core ...................................... SUCCESS [01:09 min]
[INFO] Doxia :: Modules ................................... SUCCESS [  0.418 s]
[INFO] Doxia :: APT Module ................................ SUCCESS [  2.534 s]
[INFO] Doxia :: Confluence Module ......................... SUCCESS [  2.665 s]
[INFO] Doxia :: Simplified DocBook Module ................. SUCCESS [  2.696 s]
[INFO] Doxia :: FML Module ................................ SUCCESS [  2.221 s]
[INFO] Doxia :: FO Module ................................. SUCCESS [  4.131 s]
[INFO] Doxia :: iText Module .............................. SUCCESS [  2.421 s]
[INFO] Doxia :: Latex Module .............................. SUCCESS [  2.199 s]
[INFO] Doxia :: RTF Module ................................ SUCCESS [  2.644 s]
[INFO] Doxia :: TWiki Module .............................. SUCCESS [  2.439 s]
[INFO] Doxia :: XDoc Module ............................... SUCCESS [  2.525 s]
[INFO] Doxia :: XHTML Module .............................. SUCCESS [  2.514 s]
[INFO] Doxia :: XHTML5 Module ............................. SUCCESS [  2.075 s]
[INFO] Doxia :: Markdown Module ........................... SUCCESS [  2.992 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:52 min
[INFO] Finished at: 2019-04-29T00:18:24+02:00
[INFO] ------------------------------------------------------------------------
Little-Net:maven-doxia-DOXIA-575 minfrin$ mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: /Users/minfrin/src/apache/sandbox/maven/apache-maven-3.6.0
Java version: 10.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.0.2.jdk/Contents/Home
Default locale: en_ZA, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"

I see the Jenkins job refers to a Windows build, I don't have any access to Windows alas.

Looking at the test failure, it looks like there is an additional 0a character (linefeed) that has ended up in there, but can't reproduce it my side.

**Comment by michael-o** [comment]
you can simulate this by changing {{line.separator}}.

**Comment by minfrin** [comment]
Can you try with the attached patch? There were some hard coded line feeds in the test that didn't fit the pattern, this uses the EOL variable as appears elsewhere in the code.

**Comment by michael-o** [comment]
Pushed more changes. If Jenkins is happy, I will merge.

**Pull request closed without merging**
